#!/usr/bin/env bash
# combustion: network
##########################
## Copyright (C) 2024 stendler
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.
##########################

set -e

if [ -z "$TTY" ]; then
  TTY=/dev/tty0
  echo "TTY was not set, use $TTY" >> "$TTY"
fi

echo "Combusting..." >> "$TTY"

if ! [ -f config ]; then
  echo "[combustion] script: missing config file" >> "$TTY"
  exit 1
fi

set -a # automatically export all variables
source config
set +a

## Mount /var and /home so user can be created smoothly
# (already mounted via igniton)
#mount /var
#mount /home

for module in $modules; do
  echo "[combustion] Running module $module ..." >> "$TTY"
  "./modules/$module" >> "$TTY"
  echo "[combustion] Module $module done." >> "$TTY"
done

## Clear up mounts
#umount /var
#umount /home

set +e
echo "Combustion done" >> "$TTY"
